<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $reportTitle }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
            font-size: 11px;
        }
        .header {
            text-align: center;
            margin-bottom: 25px;
            border-bottom: 3px solid #2563eb;
            padding-bottom: 20px;
        }
        .header .restaurant-name {
            font-size: 22px;
            font-weight: bold;
            color: #1e3a8a;
            margin: 0 0 5px 0;
        }
        .header .branch {
            font-size: 14px;
            color: #666;
            margin: 0 0 15px 0;
        }
        .header .report-title {
            font-size: 20px;
            font-weight: bold;
            color: #2563eb;
            margin: 10px 0;
        }
        .meta-info {
            display: table;
            width: 100%;
            margin-bottom: 25px;
            font-size: 11px;
        }
        .meta-row {
            display: table-row;
        }
        .meta-label {
            display: table-cell;
            width: 30%;
            padding: 5px 10px;
            font-weight: 600;
            color: #374151;
        }
        .meta-value {
            display: table-cell;
            padding: 5px 10px;
            color: #666;
        }
        .section-title {
            font-size: 16px;
            font-weight: bold;
            color: #1e3a8a;
            margin: 25px 0 15px 0;
            padding-bottom: 5px;
            border-bottom: 2px solid #e5e7eb;
        }
        .summary-grid {
            display: table;
            width: 100%;
            margin-bottom: 25px;
            border: 1px solid #e5e7eb;
        }
        .summary-row {
            display: table-row;
        }
        .summary-row:nth-child(even) {
            background-color: #f9fafb;
        }
        .summary-label {
            display: table-cell;
            padding: 10px 15px;
            font-weight: 600;
            color: #374151;
            width: 60%;
        }
        .summary-value {
            display: table-cell;
            padding: 10px 15px;
            text-align: right;
            font-weight: bold;
            color: #2563eb;
        }
        .summary-value.positive {
            color: #059669;
        }
        .summary-value.negative {
            color: #dc2626;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 25px;
        }
        th {
            background-color: #f3f4f6;
            padding: 10px 8px;
            text-align: left;
            border: 1px solid #e5e7eb;
            font-weight: 600;
            color: #374151;
            font-size: 10px;
        }
        td {
            padding: 8px;
            text-align: left;
            border: 1px solid #e5e7eb;
            font-size: 10px;
        }
        tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .subsection-title {
            font-size: 13px;
            font-weight: 600;
            color: #374151;
            margin: 20px 0 10px 0;
        }
        .no-data {
            text-align: center;
            padding: 20px;
            color: #9ca3af;
            font-style: italic;
        }
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            font-size: 10px;
            color: #9ca3af;
        }
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <div class="restaurant-name">{{ $data['restaurant']->restaurant_name ?? 'Restaurant Name' }}</div>
        <div class="branch">{{ $data['restaurant']->address ?? 'Branch Location' }}</div>
        <div class="report-title">{{ $reportTitle }}</div>
    </div>

    <!-- Meta Information -->
    <div class="meta-info">
        <div class="meta-row">
            <div class="meta-label">Reporting Period:</div>
            <div class="meta-value">{{ $period }}</div>
        </div>
        <div class="meta-row">
            <div class="meta-label">Generated By:</div>
            <div class="meta-value">{{ $generatedBy }}</div>
        </div>
        <div class="meta-row">
            <div class="meta-label">Date Generated:</div>
            <div class="meta-value">{{ $generatedDate }}</div>
        </div>
    </div>

    <!-- A. Summary Section -->
    <div class="section-title">A. Summary Section</div>
    <div class="summary-grid">
        <div class="summary-row">
            <div class="summary-label">Total Sales</div>
            <div class="summary-value">Php {{ number_format($data['summary']['total_sales'], 2) }}</div>
        </div>
        <div class="summary-row">
            <div class="summary-label">Total Orders</div>
            <div class="summary-value">{{ number_format($data['summary']['total_orders']) }}</div>
        </div>
        <div class="summary-row">
            <div class="summary-label">Total Expenses (Supplies/Purchases)</div>
            <div class="summary-value">Php {{ number_format($data['summary']['total_expenses'], 2) }}</div>
        </div>
        <div class="summary-row">
            <div class="summary-label">Total Spoilage Cost</div>
            <div class="summary-value">Php {{ number_format($data['summary']['total_spoilage_cost'], 2) }}</div>
        </div>
        <div class="summary-row">
            <div class="summary-label">Net Profit</div>
            <div class="summary-value {{ $data['summary']['net_profit'] >= 0 ? 'positive' : 'negative' }}">
                Php {{ number_format($data['summary']['net_profit'], 2) }}
            </div>
        </div>
    </div>

    <!-- B. Detailed Data Section -->
    <div class="section-title">B. Detailed Data Section</div>

    <!-- 1. Sales Report -->
    <div class="subsection-title">1. Sales Report</div>

    @if($showGraphs && isset($chartUrls['sales_trend']))
        <div style="text-align: center; margin: 20px 0;">
            <img src="{{ $chartUrls['sales_trend'] }}" alt="Sales Trend Chart" style="max-width: 100%; height: auto;" />
        </div>
    @endif

    @if($showGraphs && isset($chartUrls['top_items']))
        <div style="text-align: center; margin: 20px 0;">
            <img src="{{ $chartUrls['top_items'] }}" alt="Top Selling Items Chart" style="max-width: 100%; height: auto;" />
        </div>
    @endif

    @if(count($data['sales_orders']) > 0)
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Order ID</th>
                    <th class="text-right">Total Amount</th>
                    <th>Payment Type</th>
                    <th>Cashier</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['sales_orders'] as $order)
                    <tr>
                        <td>{{ $order['date'] }}</td>
                        <td>{{ $order['order_id'] }}</td>
                        <td class="text-right">Php {{ number_format($order['total_amount'], 2) }}</td>
                        <td>{{ $order['payment_type'] }}</td>
                        <td>{{ $order['cashier'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">No sales data available for this period</div>
    @endif

    <div class="page-break"></div>

    <!-- 2. Inventory Report -->
    <div class="subsection-title">2. Inventory Report</div>

    @if($showGraphs && isset($chartUrls['inventory']))
        <div style="text-align: center; margin: 20px 0;">
            <img src="{{ $chartUrls['inventory'] }}" alt="Inventory Levels Chart" style="max-width: 100%; height: auto;" />
        </div>
    @endif

    @if(count($data['inventory_items']) > 0)
        <table>
            <thead>
                <tr>
                    <th>Item Name</th>
                    <th class="text-right">Current Stock</th>
                    <th class="text-center">Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['inventory_items'] as $item)
                    <tr>
                        <td>{{ $item['item_name'] }}</td>
                        <td class="text-right">{{ $item['current_stock'] }}</td>
                        <td class="text-center">{{ $item['status'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">No inventory data available</div>
    @endif

    <!-- 3. Purchase Order Report -->
    <div class="subsection-title">3. Purchase Order Report</div>

    @if($showGraphs && isset($chartUrls['supplier_spending']))
        <div style="text-align: center; margin: 20px 0;">
            <img src="{{ $chartUrls['supplier_spending'] }}" alt="Supplier Spending Distribution" style="max-width: 100%; height: auto;" />
        </div>
    @endif

    @if(count($data['purchase_orders']) > 0)
        <table>
            <thead>
                <tr>
                    <th>PO No.</th>
                    <th>Supplier</th>
                    <th>Items</th>
                    <th class="text-right">Total Cost</th>
                    <th>Date Received</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['purchase_orders'] as $po)
                    <tr>
                        <td>{{ $po['po_no'] }}</td>
                        <td>{{ $po['supplier'] }}</td>
                        <td>{{ $po['items'] }}</td>
                        <td class="text-right">Php {{ number_format($po['total_cost'], 2) }}</td>
                        <td>{{ $po['date_received'] }}</td>
                    </tr>
                    @if(isset($po['received_items']) && $po['received_items'] !== 'Not yet received')
                    <tr>
                        <td colspan="5" style="background-color: #f9fafb; padding-left: 30px; font-size: 11px; border-top: none;">
                            <strong>Received:</strong> {{ $po['received_items'] }}
                        </td>
                    </tr>
                    @endif
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">No purchase orders for this period</div>
    @endif

    <div class="page-break"></div>

    <!-- 4. Billing Report -->
    <div class="subsection-title">4. Billing Report</div>
    @if(count($data['billing_reports']) > 0)
        <table>
            <thead>
                <tr>
                    <th>Invoice No.</th>
                    <th>Order ID</th>
                    <th>Customer</th>
                    <th class="text-right">Amount</th>
                    <th class="text-center">Status</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['billing_reports'] as $billing)
                    <tr>
                        <td>{{ $billing['invoice_no'] }}</td>
                        <td>{{ $billing['order_id'] }}</td>
                        <td>{{ $billing['customer'] }}</td>
                        <td class="text-right">Php {{ number_format($billing['amount'], 2) }}</td>
                        <td class="text-center">{{ $billing['status'] }}</td>
                        <td>{{ $billing['date'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">No billing data for this period</div>
    @endif

    <!-- 5. Spoilage Report -->
    <div class="subsection-title">5. Spoilage Report</div>

    @if($showGraphs && isset($chartUrls['spoilage']))
        <div style="text-align: center; margin: 20px 0;">
            <img src="{{ $chartUrls['spoilage'] }}" alt="Top Spoiled Items" style="max-width: 100%; height: auto;" />
        </div>
    @endif

    @if(count($data['spoilage_reports']) > 0)
        <table>
            <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Quantity</th>
                    <th>Reason</th>
                    <th>Date</th>
                    <th class="text-right">Value Lost</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['spoilage_reports'] as $spoilage)
                    <tr>
                        <td>{{ $spoilage['item_name'] }}</td>
                        <td>{{ $spoilage['quantity'] }}</td>
                        <td>{{ $spoilage['reason'] }}</td>
                        <td>{{ $spoilage['date'] }}</td>
                        <td class="text-right">Php {{ number_format($spoilage['value_lost'], 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">No spoilage incidents for this period</div>
    @endif

    <!-- Footer -->
    <div class="footer">
        <p>This is a computer-generated report. No signature is required.</p>
        <p>Generated on {{ $generatedDate }} by {{ $generatedBy }}</p>
    </div>
</body>
</html>
